//
//  YearParameters.swift
//  Bruto Neto Calculator
//
//  Created by Dimitar Stefanovski on 2/7/18.
//  Copyright © 2018 Dimitar Stefanovski. All rights reserved.
//

import Foundation

struct YearParameters {
    static let parameters: [Parameters] =
        [
            Parameters(year: 2018,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7531,
                       averageSalary: 34079),
            Parameters(year: 2017,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7456,
                       averageSalary: 32877),
            Parameters(year: 2016,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7357,
                       averageSalary: 32268),
            Parameters(year: 2015,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7320,
                       averageSalary: 31644),
            Parameters(year: 2014,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7276,
                       averageSalary: 30902),
            Parameters(year: 2013,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7269,
                       averageSalary: 30595),
            Parameters(year: 2012,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7470,
                       averageSalary: 30591),
            Parameters(year: 2011,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7316,
                       averageSalary: 30349),
            Parameters(year: 2010,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7035,
                       averageSalary: 29829),
            Parameters(year: 2009,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7000,
                       averageSalary: 27507),
            Parameters(year: 2008,
                       personalIncomeTaxRate: 0.1,
                       pensionAndDisabilityInsuranceRate: 0.18,
                       healthInsuranceFundRate: 0.073,
                       additionalHealthInsuranceAndPersonalInjuryInsuranceRate: 0.005,
                       unemploymentInsuranceFundRate: 0.012,
                       personalIncomeTaxExemptionPerMonth: 7000,
                       averageSalary: 16884)
    ]
}

